# Generated by Django 3.2.5 on 2021-10-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='last_name')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='country')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='passport')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'bookinfo',
                'verbose_name_plural': 'bookinfos',
            },
        ),
        migrations.AddField(
            model_name='roommodel',
            name='bathroom',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='bathroom'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='kitchen',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='kitchen'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='living',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='living room'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='title_uz',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='image',
            field=models.ImageField(upload_to='covers', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='price',
            field=models.CharField(max_length=32, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='BookListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_room', to='rooms.roommodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'book',
                'unique_together': {('user', 'room')},
            },
        ),
    ]
