# Generated by Django 3.2.5 on 2021-10-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20211015_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfomodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bookinfomodel',
            name='passport',
        ),
    ]
