# Generated by Django 3.2.5 on 2021-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20211019_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfomodel',
            name='arrival',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='arrival'),
        ),
        migrations.AddField(
            model_name='bookinfomodel',
            name='departure',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='departure'),
        ),
        migrations.AlterField(
            model_name='bookinfomodel',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='email'),
        ),
    ]
