# Generated by Django 3.2.5 on 2021-10-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20211020_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfomodel',
            name='departure',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='departure'),
        ),
    ]
