# Generated by Django 3.2.5 on 2021-10-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_bookinfomodel_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfomodel',
            name='arrival',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='arrival'),
        ),
    ]
