# Generated by Django 3.2.5 on 2021-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_bookinfomodel_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfomodel',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
    ]
