# Generated by Django 3.2.5 on 2021-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_bookinfomodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfomodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='phone'),
        ),
    ]
