# Generated by Django 3.2.5 on 2021-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_bookinfomodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfomodel',
            name='arrival',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='arrival'),
        ),
        migrations.AlterField(
            model_name='bookinfomodel',
            name='departure',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='departure'),
        ),
    ]
