# Generated by Django 3.2.5 on 2021-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
