# Generated by Django 3.2.5 on 2021-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_contactmodel_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='cover',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.IntegerField(max_length=14, verbose_name='phone'),
        ),
    ]
