# Generated by Django 3.2.5 on 2021-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20210731_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.FloatField(max_length=14, verbose_name='phone'),
        ),
    ]
