# Generated by Django 3.2.5 on 2021-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_bannermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
    ]
