# Generated by Django 3.2.5 on 2021-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_alter_bannermodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='phone'),
        ),
    ]
