# Generated by Django 3.2.5 on 2021-09-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_alter_contactmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='description_en',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_uz',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name_en',
            field=models.CharField(max_length=32, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name_uz',
            field=models.CharField(max_length=32, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
