# Generated by Django 3.2.5 on 2021-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_auto_20210922_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
