# Generated by Django 3.2.5 on 2021-09-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_alter_bannermodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerModel',
        ),
    ]
