# Generated by Django 3.2.5 on 2021-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0012_auto_20210923_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
    ]
