# Generated by Django 3.2.5 on 2021-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210828_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='cover'),
        ),
    ]
