# Generated by Django 3.2.5 on 2021-08-28 08:57

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_videomodel_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCoverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='cover')),
            ],
            options={
                'verbose_name': 'about cover',
                'verbose_name_plural': 'about covers',
            },
        ),
        migrations.CreateModel(
            name='AboutVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='video')),
            ],
            options={
                'verbose_name': 'about video',
                'verbose_name_plural': 'about videos',
            },
        ),
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
