# Generated by Django 3.2.5 on 2021-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210828_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcovermodel',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='description'),
        ),
    ]
