# Generated by Django 3.2.5 on 2021-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutcovermodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcovermodel',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='cover'),
        ),
    ]
