# Generated by Django 3.2.5 on 2021-08-28 09:34

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_aboutcovermodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='video')),
                ('cover', models.ImageField(null=True, upload_to='covers', verbose_name='cover')),
                ('description', models.CharField(max_length=128, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'about video',
                'verbose_name_plural': 'about videos',
            },
        ),
        migrations.DeleteModel(
            name='AboutCoverModel',
        ),
        migrations.DeleteModel(
            name='AboutVideoModel',
        ),
    ]
