# Generated by Django 3.2.5 on 2021-08-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20210828_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'about', 'verbose_name_plural': 'about'},
        ),
    ]
