# Generated by Django 3.2.5 on 2021-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_aboutmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='cover'),
        ),
    ]
