# Generated by Django 3.2.5 on 2021-09-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_aboutmodel_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='cover',
        ),
    ]
